sonar.projectKey=revisium_flowers-frontend
sonar.organization=revisium
sonar.exclusions=src/__generated__/**,**/__generated__/**,node_modules/**,build/**,dist/**,.react-router/**,.git/**
sonar.cpd.exclusions=src/__generated__/**,**/__generated__/**,node_modules/**,build/**,dist/**,.react-router/**,.git/**,src/entities/collection/model/collectionPlants.ts,src/pages/Home/model/homePageData.ts
sonar.coverage.exclusions=**/*
